-- ⚠️ SETTLEMENT CRON IS INTENTIONALLY DISABLED — DO NOT ENABLE until the go-live blockers below are resolved.
-- Holistic review (2026-06-06) found the deposit hold is VOIDED by reservation-consume at QR-scan,
-- so settlement would try to capture/refund a dead hold → permanent per-minute failures + cross-path
-- double-capture risk (legacy sweep/cancel use different conversationIds, so iyzico won't dedupe).
-- BLOCKERS (must all be resolved + verified before uncommenting the cron.schedule below):
--   1. Money model: the deposit hold must stay LIVE through the session (consume must NOT void it),
--      OR a new in-session hold is placed at unlock and recorded as the settlement target,
--      OR the abandonment penalty moves off the preauth to a different instrument.
--   2. Legacy functions (reservation-sweep/-consume/-cancel/-force-release) must set `deposit_state`
--      consistently so new rows don't desync (sweep→captured, consume→released, cancel→released/captured, force-release→released).
--   3. Confirm iyzico /payment/refund field names (paymentTransactionId + price) vs current v2 docs.
--   4. Add a failing-candidate quarantine/alert (max attempts) so a dead-hold row can't spam reservation_events forever.
-- The pure engine (decide.ts/process.ts) + its tests are correct and merge-safe; only the live trigger is gated.
--
-- Schedules the settlement Edge Function via pg_cron.
-- Mirrors 20260426130000_reservation_cron.sql + 20260605130000_session_sweep_cron.sql.
--
-- settlement CONSUMES the Phase 1 money-seam flags that reservation-sweep and
-- session-sweep only SET. Every minute it scans reservations whose deposit
-- (teminat, 20 TRY) is not yet terminal and a release/penalty/reversal flag is
-- set, and drives the right iyzico op (release / capture / refund) exactly once.
--
-- THE no-double-charge invariant (deposit_state flips ONLY after iyzico confirms
-- success; failures are retried next tick) lives in the pure core and is proven
-- by lib/server/settlement-process.test.ts. Re-running this cron on a terminal
-- row is a no-op (the decision returns 'none'), so frequent ticks are safe.
--
-- PRE-REQS (manual, one-time, via Supabase dashboard):
--   1. Project Settings → Database → Extensions: enable `pg_cron` and `pg_net`.
--      (Already enabled by 20260426130000_reservation_cron.sql; the
--       create extension if not exists below is idempotent.)
--   2. Vault (Project Settings → Vault) → add the secret (service_role_key is
--      reused from the reservation-sweep cron):
--        settlement_url      https://<project-ref>.supabase.co/functions/v1/settlement
--        service_role_key    eyJ...  (already added for reservation-sweep)
--   3. iyzico keys must be set on the project (IYZICO_API_KEY / IYZICO_SECRET_KEY /
--      IYZICO_BASE_URL) — the function responds safe (no-op) if they are missing.
--   4. Run this migration.
--
-- The cron job fires every minute (smallest pg_cron granularity). The
-- service-role JWT is read from Vault at job-run time so rotating the key takes
-- effect immediately, no migration needed.
--
-- To DISABLE the cron later:
--   select cron.unschedule('settlement');

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- make re-apply idempotent: drop any existing job of this name first
select cron.unschedule('settlement') where exists (select 1 from cron.job where jobname = 'settlement');

-- ⚠️ DISABLED pending go-live blockers (see header). The unschedule guard above stays
-- ACTIVE so re-applying this migration always removes any stale 'settlement' job.
-- To ENABLE: resolve all blockers above, then uncomment the cron.schedule below.
-- select cron.schedule(
--   'settlement',
--   '* * * * *',
--   $cmd$
--     select net.http_post(
--       url := (select decrypted_secret from vault.decrypted_secrets where name = 'settlement_url' limit 1),
--       headers := jsonb_build_object(
--         'Content-Type', 'application/json',
--         'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'service_role_key' limit 1)
--       ),
--       body := '{}'::jsonb
--     );
--   $cmd$
-- );
